# Generated by Django 2.1.11 on 2019-08-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyfansapp', '0002_personalpage_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalpage',
            table='PersonalPage',
        ),
    ]
